### ISSUE TITLE
OpenMP support

### ISSUE THREAD

**Issue by oleastre** [flathub/org.freedesktop.Sdk.Extension.llvm14#4]
Hello, I'm trying to create a build for a project (https://github.com/hanatos/vkdt) that requires llvm and OpenMP.
Unfortunately, it does not seem the llvm extension includes the libomp build, and trying to build it as part of my flatpak build leads to errors in `LLVMExports.cmake` that is part of this SDK.

What should be the best approach ? Trying to build libomp as a standalone project or include the build as part of this SDK  (I would then work on a PR to do so)

Here is what I tried: 
```
 - name: libomp
    sources:
      - type: archive
        url: https://github.com/llvm/llvm-project/releases/download/llvmorg-14.0.6/openmp-14.0.6.src.tar.xz
        sha256: 4f731ff202add030d9d68d4c6daabd91d3aeed9812e6a5b4968815cfdff0eb1f
    buildsystem: cmake
    config-opts:
      - -DCMAKE_BUILD_TYPE=Release
      - -DOPENMP_STANDALONE_BUILD=true
      - -DCLANG_LINK_CLANG_DYLIB:BOOL=ON
      - -DLLVM_DIR=/usr/lib/sdk/llvm14/lib/cmake/llvm
      - -DLLVM_BUILD_LLVM_DYLIB:BOOL=ON
      - -DLLVM_ENABLE_LLD:BOOL=ON
    build-options:
      prepend-path: "/usr/lib/sdk/llvm14/bin"
      prepend-ld-library-path: "/usr/lib/sdk/llvm14/lib"
      env:
        CC: clang
        CXX: clang++
```
